version: '3'

services: 
    nextcloud:
      container_name: nextcloud
      image: nextcloud:22.1.0
      ports: 
        - 80:80
      volumes:
      - ./web-servers/nextcloud:/var/www/html
      environment:
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
        - MYSQL_HOST=mariadb
      depends_on: 
        - mariadb
      networks: 
        - nextcloud-network

    adminer:
      container_name: adminer
      image: adminer:latest
      ports:
        - 8080:8080
      depends_on: 
        - mariadb
      networks: 
        - nextcloud-network

    mariadb:
      container_name: mariadb
      image: mariadb:10.5
      volumes:
      - ./db-servers/mariadb:/var/lib/mysql
      environment:
        - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_DATABASE=nextcloud
        - MYSQL_USER=nextcloud
      networks: 
        - nextcloud-network

networks: 
  nextcloud-network:
    name: nextcloud-network
